#!/bin/sh

ln -snf ../../test/bin/pre-commit .git/hooks/

read -p "user.name : " NAME
read -p "user.email: " EMAIL

git config rerere.enabled         1
git config push.default           current
git config branch.autosetuprebase always
git config interactive.singlekey  true
git config color.ui               auto
git config user.name              "$NAME"
git config user.email             "$EMAIL"
